name: LLVM Flang Environment
on:
  workflow_run:
    workflows: [ "LLVM Base Environment" ]
    types:
      - completed
  push:
    branches: [ "main" ]
    paths:
    - 'Dockerfile.llvm'
    - '.github/workflows/flang-clang.yaml'
  

jobs:
  flang-clang:
    if: success() || github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: [18]
        # LLVM version number
    container:
      image: ghcr.io/shinobuamasaki/base-llvm-noble-ubuntu:latest 
    env:
      IMAGE_NAME: flang-${{ matrix.version }}-noble-ubuntu
    steps:
      - name: Define env and set lowercase owner name
        shell: bash
        run: |
          # echo "OWNER_LC=$(echo "${OWNER}" | tr 'A-Z' 'a-z')" >>${GITHUB_ENV}
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Checkout repository
        uses: actions/checkout@v3
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.llvm
          target: flang
          platforms: "linux/amd64,linux/arm64"
          push: true
          build-args: |
            LLVM_VERSION=${{ matrix.version }}
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.OWNER_LC }}/${{ env.IMAGE_NAME }}:1.0.0
       


      