name: Tested with LLVM Flang on Ubuntu

on:
  workflow_run:
    workflows: [ "LLVM Flang Environment" ]
    types:
      - completed
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  flang-helloworld:
    if: success() || github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    strategy:
      matrix:
        version: [18,19,20]
    container:
      image: ghcr.io/shinobuamasaki/flang-${{ matrix.version }}-noble-ubuntu
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use flang-${{ matrix.version }} with Fortran Package Manager
        run: |
          cd example
          fpm run
      
      - name: Use flang-${{ matrix.version }} with CMake
        run: |
          cd example
          cmake -S . -B build
          cmake --build build --target run
      
