name: LLVM Flang Compiler Environment
on:
  push:
    branches: [ "main" ]

jobs:
  base-llvm:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: base-llvm-noble-ubuntu
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set lowercase owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.llvm
          push: false
          tags: |
            ghcr.io/${OWNER_LC}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${OWNER_LC}/${{ env.IMAGE_NAME }}:1.0.0
       